### ISSUE TITLE
你好，安装到最后脚本运行了，依然没有出来插件

### ISSUE THREAD

**Issue by joewongjc** [ChenghaoMou/touchbar-lyric#1]

**Comment by ChenghaoMou** [comment]
@joewongjc 如果还有问题的话，可以附上该插件的BTT配置信息。

**Comment by joewongjc** [comment]
![image](https://user-images.githubusercontent.com/12277581/63913756-e1c70380-ca63-11e9-9fa8-6c043b1b11d3.png)
现在是这样的

**Comment by joewongjc** [comment]
这样之后，touchbar是全黑没东西，应该是插件在运行但没有展示内容的情况。

**Comment by ChenghaoMou** [comment]
> 这样之后，touchbar是全黑没东西，应该是插件在运行但没有展示内容的情况。

确认是使用spotify或者apple music（非iTunes）播放音乐么？

**Comment by joewongjc** [comment]
我用的网易云诶..

**Comment by ChenghaoMou** [comment]
@joewongjc 暂时不支持网易云，只是用了网易云的歌词。网易云目前对Applescript的支持不是很好。

**Comment by joewongjc** [comment]
原来如此，谢谢

**Comment by ChenghaoMou** [comment]
Unsupported player: Netease Music.
