### ISSUE TITLE
Design suggest

### ISSUE THREAD

**Issue by camxus** [ChenghaoMou/touchbar-lyric#13]
capitalize the lines. add ".upper". done. simple
white on black works well with the keyboard letters vs green on black

thanks a lot for this

**Comment by ChenghaoMou** [comment]
You can translate lowercase to uppercase by changing the command in BTT to
```
/Users/chenghaomou/miniconda3/envs/lyric/bin/python -m touchbar_lyric  --app Spotify | tr 'a-z' 'A-Z'
```

You can also change font colors in the BTT settings
![image](https://user-images.githubusercontent.com/32014649/119375661-e982fe80-bc6f-11eb-890d-3638e6564fd7.png)
