### ISSUE TITLE
可以直接分享你的预设文件么？

### ISSUE THREAD

**Issue by wudj001** [ChenghaoMou/touchbar-lyric#16]
script的返回值是：

错误/没有返回任何内容

**Comment by ChenghaoMou** [comment]
预设文件并不能安装所需的Python库，请确保一下命令能够在终端中正确执行
```
(base) ➜  ~ which python
/Users/chenghao/miniforge3/bin/python
(base) ➜  ~ which pip
/Users/chenghao/miniforge3/bin/pip
```

使用Music 或者Spotify时，以下命令能在终端中正确执行
```
(base) ➜  ~ python -m touchbar_lyric --app Music
She wouldn't say
```

**Comment by wudj001** [comment]
感谢你！是的，可以正确执行终端：
```
python3.8 -m touchbar_lyric --app Music
白雪跑出了城堡，是贪玩的
```
但我的BTT返回值仍为：
`Error/Nothing was returned`

以下是我的设置：

```
Launch Path：
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8

Parameters：
-c

Environment Variables：
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages

Script：
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m touchbar_lyric  --app Music
```

**Comment by ChenghaoMou** [comment]
![image](https://user-images.githubusercontent.com/32014649/131352847-52563a6b-97e5-4b8d-91e4-bbf92e7c8058.png)
看上去应该是`Launch Path`设置有误

**Comment by wudj001** [comment]
已经解决，非常感谢您！
但NetEase/QQ Music好像无法使用，我是这么做的：

`$PYTHONPATH -m touchbar_lyric --app QQ Music`

`$PYTHONPATH -m touchbar_lyric --app NeteaseMusic`

**Comment by ChenghaoMou** [comment]
不用客气。暂时不支持这两个软件（它们并不支持Apple Script）这里仅仅是使用它们的歌词API而已。
