### ISSUE TITLE
How to set the lyrics to display QQ music?

### ISSUE THREAD

**Issue by shiguang0116** [ChenghaoMou/touchbar-lyric#18]
Can only show lyrics from Music and Spotify? Can you display the lyrics of QQ Music? I tried this: '/usr/bin/python3 -m touchbar_lyric --app QQMusic', but it didn't work.

**Comment by ChenghaoMou** [comment]
QQ Music is not supported because it does not support AppleScript. I cannot read what music you are playing as a result.
