### ISSUE TITLE
dont know how to set up...

### ISSUE THREAD

**Issue by 999yellin** [ChenghaoMou/touchbar-lyric#19]
i'm a total noob in the field of coding, and i just randomly saw ur project, tried everything to run in terminal but always failed.
And, i got no friend who know coding as well, maybe there is a chance u can give me some instructions...? i predict that u are chinese from ur name and profile photo, so if possible, chinese reply will be better, VERY thx if got reply... T T

**Comment by 999yellin** [comment]
search everything i can find, the only thing i've done is download the github desktop and the code files..

**Comment by ChenghaoMou** [comment]
你好 中文设置步骤可以参考 

https://github.com/ChenghaoMou/touchbar-lyric/tree/458dcf7fe047ff3978caec5dd5cde9300bcaf7e6#%E4%B8%AD%E6%96%87%E6%8C%87%E5%8D%97

**Comment by 999yellin** [comment]
非常感谢您的答疑 但是到了pip3 install touchbar_lyric --upgrade的步骤 终端报错
 error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [195 lines of output]
 running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-310
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto
      copying lib/Crypto/pct_warnings.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto
      copying lib/Crypto/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/MD2.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/SHA512.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/SHA384.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/SHA256.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/hashalgo.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/SHA.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/SHA224.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/MD4.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/HMAC.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/MD5.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      copying lib/Crypto/Hash/RIPEMD.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Hash
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/CAST.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/ARC4.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/AES.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/DES3.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/XOR.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/Blowfish.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/ARC2.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/DES.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      copying lib/Crypto/Cipher/blockalgo.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Cipher
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      copying lib/Crypto/Util/py3compat.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      copying lib/Crypto/Util/number.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      copying lib/Crypto/Util/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      copying lib/Crypto/Util/winrandom.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      copying lib/Crypto/Util/_number_new.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      copying lib/Crypto/Util/RFC1751.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      copying lib/Crypto/Util/randpool.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      copying lib/Crypto/Util/Counter.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      copying lib/Crypto/Util/asn1.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Util
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random
      copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random
      copying lib/Crypto/Random/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random
      copying lib/Crypto/Random/random.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/Fortuna
      copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/Fortuna
      copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/Fortuna
      copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/Fortuna
      copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/Fortuna
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/OSRNG
      copying lib/Crypto/Random/OSRNG/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/OSRNG
      copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/OSRNG
      copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/OSRNG
      copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Random/OSRNG
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest
      copying lib/Crypto/SelfTest/st_common.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest
      copying lib/Crypto/SelfTest/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest
 creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Cipher
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Hash
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Protocol
      copying lib/Crypto/SelfTest/Protocol/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Protocol
      copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Protocol
      copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Protocol
      copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Protocol
      copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Protocol
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/PublicKey
      copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/PublicKey
      copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/PublicKey
      copying lib/Crypto/SelfTest/PublicKey/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/PublicKey
      copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/PublicKey
      copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/PublicKey
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random
      copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random
      copying lib/Crypto/SelfTest/Random/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random
      copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random
      copying lib/Crypto/SelfTest/Random/test__UserFriendlyRNG.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/Fortuna
      copying lib/Crypto/SelfTest/Random/Fortuna/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/Fortuna
      copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/Fortuna
      copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/Fortuna
      copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/Fortuna
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/OSRNG
      copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/OSRNG
      copying lib/Crypto/SelfTest/Random/OSRNG/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/OSRNG
      copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/OSRNG
      copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/OSRNG
      copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/OSRNG
      copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Random/OSRNG
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Util
      copying lib/Crypto/SelfTest/Util/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Util
      copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Util
      copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Util
      copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Util
      copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Util
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Signature
      copying lib/Crypto/SelfTest/Signature/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Signature
      copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Signature
      copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/SelfTest/Signature
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/Protocol
 copying lib/Crypto/Protocol/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Protocol
      copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Protocol
      copying lib/Crypto/Protocol/KDF.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Protocol
      copying lib/Crypto/Protocol/Chaffing.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Protocol
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/PublicKey
      copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/PublicKey
      copying lib/Crypto/PublicKey/RSA.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/PublicKey
      copying lib/Crypto/PublicKey/pubkey.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/PublicKey
      copying lib/Crypto/PublicKey/_DSA.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/PublicKey
      copying lib/Crypto/PublicKey/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/PublicKey
      copying lib/Crypto/PublicKey/_RSA.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/PublicKey
      copying lib/Crypto/PublicKey/DSA.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/PublicKey
      copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/PublicKey
      creating build/lib.macosx-10.9-universal2-cpython-310/Crypto/Signature
      copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Signature
      copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Signature
      copying lib/Crypto/Signature/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/Crypto/Signature
      running build_ext
      running build_configure
      checking for gcc... gcc
      checking whether the C compiler works... no
      configure: error: in `/private/var/folders/jk/cytf9nd50k98brk0fvqbzzy80000gn/T/pip-install-a7xaf377/pycrypto_f85dd09c9e9547e49b872af9d8d160e7':
      configure: error: C compiler cannot create executables
      See `config.log' for more details
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/jk/cytf9nd50k98brk0fvqbzzy80000gn/T/pip-install-a7xaf377/pycrypto_f85dd09c9e9547e49b872af9d8d160e7/setup.py", line 456, in <module>
          core.setup(**kw)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/jk/cytf9nd50k98brk0fvqbzzy80000gn/T/pip-install-a7xaf377/pycrypto_f85dd09c9e9547e49b872af9d8d160e7/setup.py", line 251, in run
          self.run_command(cmd_name)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/jk/cytf9nd50k98brk0fvqbzzy80000gn/T/pip-install-a7xaf377/pycrypto_f85dd09c9e9547e49b872af9d8d160e7/setup.py", line 278, in run
          raise RuntimeError("autoconf error")
      RuntimeError: autoconf error
      [end of output]

**Comment by 999yellin** [comment]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
Failed to build pycrypto
Installing collected packages: pycrypto, pyaes, hanziconv, applescript, urllib3, loguru, idna, diskcache, coverage, click, charset-normalizer, certifi, typer, requests, qqmusic-api, touchbar_lyric
  Running setup.py install for pycrypto ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pycrypto did not run successfully.
  │ exit code: 1
  ╰─> [199 lines of output]

**Comment by 999yellin** [comment]
两个output我都暂时省略了 好像篇幅太长 然后最后接着是 note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycrypto

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

如需要这两段output 烦请留言 我再发上来

**Comment by 999yellin** [comment]
如果无视这个error 直接往btt里面放那个json文件 就是如图这样的情况
![image](https://user-images.githubusercontent.com/110706910/183243550-bfa512cc-7078-432b-935b-fc5f48ba1401.png)
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/110706910/183243563-0a520f55-ee33-4efa-a35f-8fda1d19eca5.png">

**Comment by ChenghaoMou** [comment]
@999yellin 第一个问题应该是macos缺少编译器的结果，你可以在终端执行`xcode-select --install` 进行安装。安装完成后再进行其他步骤。

以下是更新的中文步骤

---
检查 macOS 系统自带的 Python3 ，在系统自带的 Terminal 应用中输入以下命令
```
which python3
```
*返回输出的路径信息后面会使用

安装 pip
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
```
安装 touchbar-lyric
```
pip3 install touchbar_lyric --upgrade
```
BTT设置
1. 复制 lyric.json 里面的内容，在BTT的Touch Bar 配置界面直接粘贴
2. 在右侧脚本区域， 把 $PYTHONPATH 换成第一步中的路径

**Comment by 999yellin** [comment]
顺利配置成功 万分感谢 祝顺利！
顺便问一个问题 我观察到歌词和实际的延迟不一 这个歌词是跟着设置里面1hz的刷新率来走的吗 还是自动搜集的歌词和时序？

**Comment by ChenghaoMou** [comment]
不用谢！

两种情况都有可能造成不同步的情况，延迟主要还是因为程序需要随时分析歌曲播放信息然后调整歌词。
