### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rignaneseleo** [ChenghaoMou/touchbar-lyric#2]
Hi, thanks for sharing this plugin!
I followed your instructions but although I can't run whereis python3 on my mac (it returns nothing), I've put `/usr/local/bin/python3 -m touchbar_lyric` that looks like my python3 path and I see no lyrics.

It doesn't show anything, before putting the path at least I had the error for the python wrong path, now it's just an empty space.

How can I solve this? I'm not using the proxy API.

**Comment by ChenghaoMou** [comment]
@rignaneseleo  When you said it didn't show anything, were you playing any music on Spotify/iTunes/Music? Even if there is no lyric, the plugin should show a 'No lyric' button. One thing you could try to pin down the problem is to execute  `/usr/local/bin/python3 -m touchbar_lyric` in your terminal when playing music. No proxy should be fine.

**Comment by rignaneseleo** [comment]
Well, I tried also from the console and it doesn’t show me the lyrics.
I’ve followed the guide but looks like something is missing or not configured. What should I do?

Thanks!

**Comment by ChenghaoMou** [comment]
Can you update touchbar_lyric to 0.1.6 and execute `/usr/local/bin/python3 -m touchbar_lyric --debug`?

**Comment by rignaneseleo** [comment]
Sure, here it is:
```
> /usr/local/bin/python3 -m touchbar_lyric --debug
> Not playing
```
I'm playing a Red Hot Chili Peppers with spotify at the moment 🤘🏼

**Comment by ChenghaoMou** [comment]
Ha, itunes and music(catalina) is incompatible with each other. That's why the script cannot get any information about the current track. Please update touchbar_lyric to 0.1.8 and let me know if the problem still exists.  Thanks so much for the help!!

**Comment by rignaneseleo** [comment]
I've updated but same error:
```
 /usr/local/bin/python3 -m touchbar_lyric --debug
Not playing
```

I don't use iTunes or music, I only use Spotify.
Anyway, why my touchbar doesn't show even an error?

**Comment by ChenghaoMou** [comment]
Weird. Can you update it to 0.1.9? I added more debugging info. You might want to update it multiple times cuz pip caching might give you a wrong version.

**Comment by rignaneseleo** [comment]
This is the log from the version 0.1.9:

> /usr/local/bin/python3 -m touchbar_lyric --debug
> /var/folders/q1/gzsly8jn68gf1_92dp04s9k40000gn/T/tmpihgc545v:497:502: script error: Expected “,” or “}” but found identifier. (-2741) 1
> Not playing

Hope it helps!

**Comment by ChenghaoMou** [comment]
@rignaneseleo It is the error that I included in 0.1.4 for support of iTunes. It should be resolved by 0.1.9. But if you are on Mojave, it is possible that the piece of code for `Music` is incompatible with the system. 

here is what you can try:

clone the repo to your machine;

edit touchbar_lyric/__init__.py 
change the code in `get_info` (basically change `Music` to `iTunes`)
```python
else if application "Music" is running then
    tell application "Music"
        set currentInfo to {"Music", artist of current track, "###", name of current track, player position, player state, duration of current track}
    end tell
end if
```

to 
```python
else if application "iTunes" is running then
    tell application "iTunes"
        set currentInfo to {"iTunes", artist of current track, "###", name of current track, player position, player state, duration of current track}
    end tell
end if
```
the execute the following command in the directory of the repo:

```bash
pip install --editable .
```

**Comment by rignaneseleo** [comment]
I'm on Mojave 10.14.6!
I'll try this. Thanks.

**Comment by rignaneseleo** [comment]
I directly removed everything that was not Spotify:
```
 on run
                if application "Spotify" is running then
                    tell application "Spotify"
                        set currentInfo to {"Spotify", artist of current track, "###", name of current track, player position, player state, duration of current track}
                    end tell
                end if
                return currentInfo
            end run
```
And it works! Super cool.
It needs some UI imporvements IMHO. I'll try to make some changes and push it here!
Thanks!
