### ISSUE TITLE
No module named touchbar_lyric...

### ISSUE THREAD

**Issue by plumage33** [ChenghaoMou/touchbar-lyric#21]
你好！謝謝你的分享～

請問已經依照步驟設定，但最後BTT & touch bar上卻持續顯示
「/Library/Frameworks/Python.framework/Versions/3.11/bin/python3: No module named touchbar_lyric」

請問後續要怎麼處理才能順利運作呢？謝謝～

**Comment by ChenghaoMou** [comment]
可以尝试在终端执行
```
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install touchbar_lyric
```

**Comment by plumage33** [comment]
你好，
執行後出現以下錯誤訊息：
<img width="616" alt="截圖 2022-12-02 上午10 20 02" src="https://user-images.githubusercontent.com/119588934/205200404-8b7a40ef-f95e-4b90-bd49-b689a7f04ad5.png">

請問該如何處理呢？謝謝

**Comment by ChenghaoMou** [comment]
看上去应该是Python版本（3.11）和依赖的程序（regex）不兼容，我抽空看看能不能从我这里解决。

**Comment by plumage33** [comment]
謝謝你！再麻煩了～

**Comment by ChenghaoMou** [comment]
@plumage33 我试了一下，发现不是Python版本问题（我本地Python3.11安装没有出现任何问题）。或许是pip版本问题，可以执行一下步骤试试：
```
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install --upgrade pip
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install --upgrade wheel
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install --upgrade setuptools
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install touchbar_lyric
```

**Comment by plumage33** [comment]
你好，執行最後一項時出現以下訊息
<img width="611" alt="image" src="https://user-images.githubusercontent.com/119588934/206951286-202ba796-58ca-4edc-a379-23e08b77370f.png">

**Comment by ChenghaoMou** [comment]
可以执行
```
xcode-select --install
```
安装macos需要的程序依赖，应该会有图形界面出现，安装完成后再执行
```
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install touchbar_lyric
```
应该就可以了。

**Comment by plumage33** [comment]
你好！沒有跳出錯誤訊息了
但開啟spotify播放時，touch bar還是沒有出現歌詞

BTT的訊息如下
![截圖 2022-12-12 下午1 22 11](https://user-images.githubusercontent.com/119588934/206966759-740d3608-5f0f-4b73-a6e9-5da16531dd69.png)

請問有其他解決方法嗎？還是我的步驟有錯誤？
安裝成功後應該是Spotify播放音樂時，就會自動出現歌詞？
謝謝～

**Comment by plumage33** [comment]
你好，BTT換成出現這個訊息：
<img width="556" alt="image" src="https://user-images.githubusercontent.com/119588934/207213933-c424eab8-8c0c-40e2-bb7a-aa18ac19c6a5.png">

touch bar上也顯示"Try '__main__.py --help' for help."

**Comment by ChenghaoMou** [comment]
新版本不需要设置bg和fc参数，可以直接在BTT中设置。请删除Script中`—bg 51,204,153 —fc 255,255,255`

**Comment by plumage33** [comment]
成功了！非常謝謝你 🙏

**Comment by ChenghaoMou** [comment]
不用客气！
