### ISSUE TITLE
歌词闪烁，歌词不同步，歌词参数不知道怎么调

### ISSUE THREAD

**Issue by SuQiANQAQ** [ChenghaoMou/touchbar-lyric#26]
歌词闪烁： 正常的歌词会和开头的编曲之类的交替闪烁（偶发）
歌词不同步：有时候会慢一两秒，有时候又正常
歌词参数：--rainbow fs大小都在哪里调呀

ps：谢谢作者，真的是个很棒的插件。

**Comment by SuQiANQAQ** [comment]
歌词闪烁：一开始的时候会有，播放一会就没有了
歌词不同步：好像是偶发性的
歌词参数，这个是不是不能使用了呀，fs好像也没了

**Comment by ChenghaoMou** [comment]
谢谢你的Issue

1. 闪烁是因为每首新歌搜索和下载歌词时间大大长于刷新时间，短时间内所有之前的歌词都会一起闪现。遗憾的事，目前没有解决办法。
2. 同步问题主要是歌词信息不匹配。主要原因是搜索接口非官方，所以质量没法保证。
3. 歌词参数新版本中不再支持，可以直接在BTT设置字号。其他参数因为耗电等考量去掉了。

**Comment by SuQiANQAQ** [comment]
这btt确实耗电离谱
