### ISSUE TITLE
No module named touchbar_lyric

### ISSUE THREAD

**Issue by hsuehpascal** [ChenghaoMou/touchbar-lyric#3]
Hi,

Thanks for the awesome plugin. However, I cannot seem to get it to work as my Touch Bar displays only 
`/Library/Developer/CommandLineTools/usr/bin/python3: No module named  touchbar_lyric`

I've run the command in Terminal and it gave back the correct lyrics without a problem. However I cannot get the lyrics to display on my Touch Bar. For the record, I'm quite a noob at python, so please do forgive me if I'm making some basic mistakes.

Could you please give me some instructions on how I can solve this problem? Thanks in advance!

**Comment by hsuehpascal** [comment]
Update: I tried restarting the machine, and now even running the script in Terminal returns 
`/Library/Developer/CommandLineTools/usr/bin/python3: No module named touchbar_lyric`

Could you please point out what I did wrong?

**Comment by ChenghaoMou** [comment]
@hsuehpascal  can you show me the following commands' output in terminal?

- `which python3`
- `which pip3`
- `pip3 list`

**Comment by hsuehpascal** [comment]
Hi,

Thanks for the prompt reply! The commands you suggested gave these:
```

- which python3

/Library/Frameworks/Python.framework/Versions/3.8/bin/python3

- which pip3

/Library/Frameworks/Python.framework/Versions/3.8/bin/pip3

- pip3 list

Package        Version  
-------------- ---------
argh           0.26.2   
cachier        1.2.6    
certifi        2019.9.11
chardet        3.0.4    
hanziconv      0.3.2    
idna           2.8      
osascript      2019.4.13
pathtools      0.1.2    
pinyin         0.4.0    
pip            19.3.1   
portalocker    1.5.2    
psutil         5.6.5    
public         2019.4.13
PyYAML         5.1.2    
requests       2.22.0   
runcmd         2019.4.13
setuptools     41.2.0   
soupsieve      1.9.5    
temp           2019.4.13
touchbar-lyric 0.1.9    
urllib3        1.25.7   
watchdog       0.9.0   
```

Again I'm really new to this so maybe I'm making some basic mistakes unknowingly. My apologies.

**Comment by ChenghaoMou** [comment]
It seems that you are using a wrong python3 for BTT.

For step 2 in configuration, your `${PYTHONPATH}` should be `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3`  instead of `/Library/Developer/CommandLineTools/usr/bin/python3`

**Comment by hsuehpascal** [comment]
Hi,

After changing the script directory as instructed I finally got it to work, though I had to do an extra step and run the following command.
`pip3 install pycryptodome`

Thank you so much for the help. I really enjoy this cool plugin!

P.S. Are there any plans to support transitions between traditional and simplified Chinese, or pulling traditional Chinese lyrics?

**Comment by ChenghaoMou** [comment]
Currently no plan for traditional/simplified Chinese change. The API I have been using is not exactly traditional Chinese friendly. 

I am closing this issue for now. If you have any other questions, feel free to open another.
