### ISSUE TITLE
Possibility of using Musixmatch as lyrics source?

### ISSUE THREAD

**Issue by JCsplash** [ChenghaoMou/touchbar-lyric#5]
Hey @ChenghaoMou  thank you for the great library! Do you see any possibility of scraping lyrics from Musixmatch? Netease sometimes has inaccurate lyrics and missing songs; i think Musixmatch would be much more complete. 

However it seems like Musixmatch is pretty closed off. It's official API (the free version) doesn’t allow for synced lyrics. I’m wondering if you see any workarounds here? Or do you think Netease is our best choice?

**Comment by ChenghaoMou** [comment]
Glad you like it, and thanks for the suggestion.

Musixmatch does have a commercial API [Link](https://developer.musixmatch.com/plans) for synced lyrics and they actually had a pretty cool prototype [Youtube](https://www.youtube.com/watch?v=XzoW7pmpxtI) and people are constantly badgering them for this feature as well [Twitter](https://twitter.com/musixmatch/status/819247987062931468?lang=en). I just couldn’t wait any longer. 

Unfortunately, the lyrics are considered copyrighted, especially for a company like Musixmatch, in a country like America. There might be legal issues if I just hack my way to get my hands on the synced lyrics that they profit on (which I tried and failed). So Netease is a much safer and more accessible choice.

However, there are few other ways to improve the lyric quality and stability from other Chinese music platforms (QQ, Kugou, Xiami, TTPod etc.) just like what [LyricsX](https://github.com/ddddxxx/LyricsX) is doing.

**Comment by JCsplash** [comment]
@ChenghaoMou Totally understand and apologies for the late response. I ended up using LyricsX and sending the lyrics over to BTT via Webserver which works great. Thanks again for writing touchbar-lyric!
