### ISSUE TITLE
Cannot install touchbar_lyric

### ISSUE THREAD

**Issue by utkuuozcan** [ChenghaoMou/touchbar-lyric#8]
When i run _pip3 install touchbar_lyric --upgrade_ , collecting things runs but after that "#error Unsupported architecture" comes up. Is it about "macOS doesn't support 32bit anymore" thing?

Note: When i run _python3 get-pip.py_ it installed pip successfully but there was a warning. "WARNING: The scripts pip, pip3 and pip3.8 are installed in '/Users/utku/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location."

- which python3
/usr/bin/python3

- which pip3
/usr/bin/pip3

-pip3 list
Package    Version
---------- -------
pip        20.2.3
setuptools 41.2.0
six        1.15.0
wheel      0.33.1

**Comment by ChenghaoMou** [comment]
Can you show me the whole output in your terminal? It looks like a dependency issue

**Comment by ChenghaoMou** [comment]
I did some search on the internet, it looks like whatever python the Xcode installed does not work very well with some extensions, so it is best to install a python directly from python.org https://github.com/ycm-core/YouCompleteMe/issues/3770#issuecomment-700841907

**Comment by utkuuozcan** [comment]
Before I installed python from python.org this screenshot was my terminal output.
<img width="1440" alt="Screen Shot 2021-01-22 at 14 51 41" src="https://user-images.githubusercontent.com/72924908/105488422-a402f480-5cc2-11eb-9367-0d492f5cbeba.png">

Then I installed python from python.org(which is Python 3.9.1) and I run "pip3 install touchbar_lyric --upgrade" . But nothing chanced. Here is my debug output
<img width="1051" alt="Screen Shot 2021-01-22 at 15 05 32" src="https://user-images.githubusercontent.com/72924908/105488847-58047f80-5cc3-11eb-9554-726038ecc7f9.png">

And this my BetterTouchTool config in case you need.
<img width="1440" alt="Screen Shot 2021-01-22 at 15 09 49" src="https://user-images.githubusercontent.com/72924908/105489170-e416a700-5cc3-11eb-81da-78aa0c673128.png">

By the way thanks for your help.

**Comment by ChenghaoMou** [comment]
Looks like the configuration in BTT is incorrect, you should paste the copied content when you open the app instead of pasting it in a script area. It should create a widget like this:

![image](https://user-images.githubusercontent.com/32014649/105553478-53879900-5cba-11eb-81f4-86c338fdcd27.png)

I also notice that you have a warning "Your custom Touch Bar is currently hidden", you can click the warning to show it

**Comment by jkdiazb** [comment]
Hi Chenghao,
I have a similar issue, but I do not understand where I should copy the content of lyric.json instead in the Script area.

I really appreciate any help you can provide.
Javiera

**Comment by bdunogier** [comment]
Just paste it when you see the + button for adding a trigger, @jkdiazb, it will create a new entry in the list.
