### ISSUE TITLE
Some lyrics are wrong

### ISSUE THREAD

**Issue by rignaneseleo** [ChenghaoMou/touchbar-lyric#9]
Hi, great project!
I'd like to report that sometimes it doesn't catch the right song and it shows the lyrics of another one. 

Do you send to the server both the title and the author? because it seems that only the title is considered. Try to listen Mattafix songs on Spotify and the half of the songs are not regognized.

I would rather prefer not have a lyrics than have a wrong one (especially it is in Chinese language that I can't read).
Can you add a filter for this?

**Comment by ChenghaoMou** [comment]
So far the logic is to find the best possible match, even if the match is not accurate at all. I am thinking about adding another flag `--accurate` to stop displaying anything if no lyric if found, does that sound like a solution to you?

**Comment by rignaneseleo** [comment]
Yes, it sounds good.

**Comment by ChenghaoMou** [comment]
Cool, I will work on this over the weekend.

**Comment by ChenghaoMou** [comment]
`0.5.3` is out, feel free to upgrade the package and turn on accurate mode!

**Comment by DonB7** [comment]
> `0.5.3` is out, feel free to upgrade the package and turn on accurate mode!

Please, how can I find my actual version and how to upgrade to the latest? This is the exect same issue I am having
